### DISCUSSION TITLE
Reporting fuzzer failures

### DISCUSSION THREAD

**Discussion by Porges** [microsoft/onefuzz#2512] [Ideas]
At the moment if a fuzzer exits for some unknown reason we don't do anything special, and the fuzzer will be restarted.

At the very least we should report the exit code information, and we also have had requests (#2313) to capture mini/core dumps from the fuzzer process.

We will need some way to report this information to the users, so I'm opening up this discussion to get some ideas.

We probably will want to report the information via the API, maybe something along the lines of:

```
unexpected_exits:
- timestamp: "…"
  exit_code: 12345
  dump_file: "https://…"
  run_log: "https://…" # run-specific stderr or stdout log
```
